### ISSUE TITLE
Please clarify project license

### ISSUE THREAD

**Issue by Zorin95670** [Naouak/EBU-STL-tools#5]
I work on packaging your great project for debian and I need license.

Is that possible to add license on your project =D ?

**Comment by Naouak** [comment]
Does WTFPL works for Debian ? If not, do you have any license you recommend (I don't really care which license as long as I'm not accountable for others people use of the code and it stays free).

**Comment by Zorin95670** [comment]
In `/usr/share/common-licenses` on Debian, BSD license is like WTFPL in more formal.
[BSD.txt](https://github.com/Naouak/EBU-STL-tools/files/2956366/BSD.txt)

**Comment by Zorin95670** [comment]
So you, if this license is suitable for you, you can use it :)
